"""initial schema

Revision ID: 557f8300ece0
Revises: 
Create Date: 2026-09-27 16:04:46.574930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '557f8300ece0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airfields',
    sa.Column('icao', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('icao')
    )
    op.create_table('gliders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('ogn_device_id', sa.String(length=16), nullable=True),
    sa.Column('claim_token', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_token'),
    sa.UniqueConstraint('ogn_device_id'),
    sa.UniqueConstraint('registration')
    )
    op.create_table('pilots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PILOT', 'ADMIN', name='pilotrole'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='pilotstatus'), nullable=False),
    sa.Column('vereinsflieger_member_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pilots_email'), 'pilots', ['email'], unique=True)
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('glider_id', sa.Integer(), nullable=True),
    sa.Column('pilot_id', sa.Integer(), nullable=True),
    sa.Column('takeoff_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('landing_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('takeoff_airfield_icao', sa.String(length=4), nullable=True),
    sa.Column('landing_airfield_icao', sa.String(length=4), nullable=True),
    sa.Column('landing_latitude', sa.Float(), nullable=True),
    sa.Column('landing_longitude', sa.Float(), nullable=True),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('AUTO', 'MANUAL', name='flightsource'), nullable=False),
    sa.Column('verified_by_pilot', sa.Boolean(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vereinsflieger_external_id', sa.String(length=64), nullable=True),
    sa.Column('vereinsflieger_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['glider_id'], ['gliders.id'], ),
    sa.ForeignKeyConstraint(['landing_airfield_icao'], ['airfields.icao'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.ForeignKeyConstraint(['takeoff_airfield_icao'], ['airfields.icao'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('flight_audit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_pilot_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_pilot_id'], ['pilots.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glider_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('glider_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['glider_id'], ['gliders.id'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('glider_claims')
    op.drop_table('flight_audit_entries')
    op.drop_table('password_reset_tokens')
    op.drop_table('flights')
    op.drop_index(op.f('ix_pilots_email'), table_name='pilots')
    op.drop_table('pilots')
    op.drop_table('gliders')
    op.drop_table('airfields')
    # ### end Alembic commands ###
